-- Ejecutar en Supabase -> SQL Editor (una sola vez)
alter table actas add column if not exists materia_id bigint references materias(id) on delete set null;
alter table actas add column if not exists periodo text;
alter table actas add column if not exists estado text default 'pendiente';
alter table actas add column if not exists implicaciones_legales text;

-- Asistencia por materia (para que cada profesor registre la suya, y se pueda
-- consultar la asistencia consolidada de un estudiante en todas sus materias)
alter table asistencia drop constraint if exists asistencia_estudiante_id_fecha_key;
alter table asistencia add column if not exists materia_id bigint references materias(id) on delete set null;
alter table asistencia add column if not exists docente_id uuid references auth.users(id) on delete set null;
-- Si el paso anterior de "drop constraint" no encontró el nombre exacto,
-- revisa en Supabase -> Table Editor -> asistencia -> Constraints cuál es
-- el nombre real de la restricción UNIQUE(estudiante_id, fecha) y bórrala
-- manualmente antes de correr la siguiente línea.
alter table asistencia drop constraint if exists asistencia_estudiante_fecha_materia_key;
drop index if exists asistencia_estudiante_fecha_materia_key;
alter table asistencia add constraint asistencia_estudiante_fecha_materia_key unique (estudiante_id, fecha, materia_id);

-- Catálogo editable de comportamientos convivenciales y académicos
-- (para no depender solo de Leve/Grave/Gravísima ni de una única plantilla académica)
create table if not exists comportamientos (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  categoria text not null check (categoria in ('convivencial','academico')),
  nombre text not null,
  articulo text,
  plazo_dias integer,
  implicaciones_legales text,
  plantilla text,
  creado_en timestamptz default now()
);

alter table comportamientos enable row level security;

drop policy if exists "comportamientos_select_todos" on comportamientos;
create policy "comportamientos_select_todos"
  on comportamientos for select using (true);

drop policy if exists "comportamientos_insert_propio" on comportamientos;
create policy "comportamientos_insert_propio"
  on comportamientos for insert with check (auth.uid() = docente_id);

drop policy if exists "comportamientos_delete_propio" on comportamientos;
create policy "comportamientos_delete_propio"
  on comportamientos for delete using (auth.uid() = docente_id);

-- Catálogo de reinos/equipos: nombre, color y logo personalizables
create table if not exists reinos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  color text,
  logo_url text,
  creado_en timestamptz default now()
);

alter table reinos enable row level security;

drop policy if exists "reinos_select_todos" on reinos;
create policy "reinos_select_todos"
  on reinos for select using (true);

drop policy if exists "reinos_write_todos" on reinos;
create policy "reinos_write_todos"
  on reinos for all using (true) with check (true);

-- Rol de administrador para docentes
alter table profesores add column if not exists es_admin boolean default false;

drop policy if exists "profesores_update_es_admin" on profesores;
create policy "profesores_update_es_admin"
  on profesores for update using (true) with check (true);

-- Procesos de inclusión (PIAR / DUA): marca visible + ajustes razonables + bitácora de seguimiento
alter table estudiantes add column if not exists piar boolean default false;
alter table estudiantes add column if not exists dua boolean default false;
alter table estudiantes add column if not exists ajustes_inclusion text;

create table if not exists seguimiento_inclusion (
  id bigint generated by default as identity primary key,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  docente_id uuid references auth.users(id) on delete set null,
  materia_id bigint references materias(id) on delete set null,
  fecha date not null default current_date,
  tipo text,
  observacion text not null,
  creado_en timestamptz default now()
);

alter table seguimiento_inclusion enable row level security;

drop policy if exists "seguimiento_inclusion_select" on seguimiento_inclusion;
create policy "seguimiento_inclusion_select"
  on seguimiento_inclusion for select using (true);

drop policy if exists "seguimiento_inclusion_insert" on seguimiento_inclusion;
create policy "seguimiento_inclusion_insert"
  on seguimiento_inclusion for insert with check (true);

drop policy if exists "seguimiento_inclusion_delete" on seguimiento_inclusion;
create policy "seguimiento_inclusion_delete"
  on seguimiento_inclusion for delete using (true);

-- Apellido explícito para forzar el orden alfabético correcto (en vez de adivinarlo del nombre completo)
alter table estudiantes add column if not exists apellidos text;

-- Guarda la nota que tenía el estudiante antes de superar la nivelación,
-- para poder mostrarla entre paréntesis junto a la nota final ajustada.
alter table nivelacion add column if not exists nota_original numeric;

-- Número de documento del estudiante (para mostrar solo los últimos 4 dígitos en las actas oficiales)
alter table estudiantes add column if not exists documento text;

-- Directorio de acudientes: padre, madre y contacto de emergencia por estudiante
create table if not exists acudientes (
  id bigint generated by default as identity primary key,
  estudiante_id bigint references estudiantes(id) on delete cascade unique,
  nombre_padre text,
  telefono_padre text,
  nombre_madre text,
  telefono_madre text,
  contacto_emergencia_nombre text,
  contacto_emergencia_telefono text,
  contacto_emergencia_relacion text,
  direccion text,
  actualizado_en timestamptz default now()
);

alter table acudientes enable row level security;

drop policy if exists "acudientes_select_todos" on acudientes;
create policy "acudientes_select_todos"
  on acudientes for select using (true);

drop policy if exists "acudientes_write_todos" on acudientes;
create policy "acudientes_write_todos"
  on acudientes for all using (true) with check (true);

-- Horario de clases: cada docente registra el suyo, pero todos pueden verlos
create table if not exists horario (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete cascade,
  materia_id bigint references materias(id) on delete set null,
  grado_id text,
  nombre_actividad text,
  dia_semana integer not null check (dia_semana between 1 and 6),
  hora_inicio time not null,
  hora_fin time not null,
  creado_en timestamptz default now()
);

alter table horario enable row level security;

drop policy if exists "horario_select_todos" on horario;
create policy "horario_select_todos"
  on horario for select using (true);

drop policy if exists "horario_insert_propio" on horario;
create policy "horario_insert_propio"
  on horario for insert with check (auth.uid() = docente_id);

drop policy if exists "horario_update_propio" on horario;
create policy "horario_update_propio"
  on horario for update using (auth.uid() = docente_id);

drop policy if exists "horario_delete_propio" on horario;
create policy "horario_delete_propio"
  on horario for delete using (auth.uid() = docente_id);

-- Cronograma de actividades: institucionales, académicas y convivenciales mezcladas
create table if not exists cronograma (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  titulo text not null,
  descripcion text,
  tipo text not null default 'institucional' check (tipo in ('institucional','academico','convivencial','festivo','otro')),
  fecha date not null,
  fecha_fin date,
  grado_id text,
  creado_en timestamptz default now()
);

alter table cronograma enable row level security;

drop policy if exists "cronograma_select_todos" on cronograma;
create policy "cronograma_select_todos"
  on cronograma for select using (true);

drop policy if exists "cronograma_insert_todos" on cronograma;
create policy "cronograma_insert_todos"
  on cronograma for insert with check (true);

drop policy if exists "cronograma_update_todos" on cronograma;
create policy "cronograma_update_todos"
  on cronograma for update using (true);

drop policy if exists "cronograma_delete_todos" on cronograma;
create policy "cronograma_delete_todos"
  on cronograma for delete using (true);

-- Planeaciones: plan de estudios (unidades/temas) y planeación de clases por periodo
create table if not exists planeaciones (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete cascade,
  materia_id bigint references materias(id) on delete cascade,
  grado_id text,
  periodo text not null,
  tipo text not null default 'unidad' check (tipo in ('unidad','clase')),
  unidad_id bigint references planeaciones(id) on delete cascade,
  orden integer default 0,
  titulo text not null,
  objetivo text,
  contenido text,
  fecha date,
  estado text not null default 'borrador' check (estado in ('borrador','publicado')),
  creado_en timestamptz default now()
);

alter table planeaciones enable row level security;

drop policy if exists "planeaciones_select_todos" on planeaciones;
create policy "planeaciones_select_todos"
  on planeaciones for select using (true);

drop policy if exists "planeaciones_insert_propio" on planeaciones;
create policy "planeaciones_insert_propio"
  on planeaciones for insert with check (auth.uid() = docente_id);

drop policy if exists "planeaciones_update_propio" on planeaciones;
create policy "planeaciones_update_propio"
  on planeaciones for update using (auth.uid() = docente_id);

drop policy if exists "planeaciones_delete_propio" on planeaciones;
create policy "planeaciones_delete_propio"
  on planeaciones for delete using (auth.uid() = docente_id);

-- Recursos (Google Drive / Docs / Forms u otro enlace) asociados a una unidad o clase
create table if not exists planeacion_recursos (
  id bigint generated by default as identity primary key,
  planeacion_id bigint references planeaciones(id) on delete cascade,
  tipo text not null default 'otro' check (tipo in ('drive','docs','forms','otro')),
  titulo text,
  url text not null,
  creado_en timestamptz default now()
);

alter table planeacion_recursos enable row level security;

drop policy if exists "planeacion_recursos_select_todos" on planeacion_recursos;
create policy "planeacion_recursos_select_todos"
  on planeacion_recursos for select using (true);

drop policy if exists "planeacion_recursos_write_todos" on planeacion_recursos;
create policy "planeacion_recursos_write_todos"
  on planeacion_recursos for all using (true) with check (true);

-- Tareas organizadas por unidad/tema
create table if not exists planeacion_tareas (
  id bigint generated by default as identity primary key,
  planeacion_id bigint references planeaciones(id) on delete cascade,
  titulo text not null,
  descripcion text,
  tipo text not null default 'tarea' check (tipo in ('tarea','lectura','proyecto','evaluacion')),
  fecha_entrega date,
  recurso_url text,
  creado_en timestamptz default now()
);

alter table planeacion_tareas enable row level security;

drop policy if exists "planeacion_tareas_select_todos" on planeacion_tareas;
create policy "planeacion_tareas_select_todos"
  on planeacion_tareas for select using (true);

drop policy if exists "planeacion_tareas_write_todos" on planeacion_tareas;
create policy "planeacion_tareas_write_todos"
  on planeacion_tareas for all using (true) with check (true);

-- Rúbrica sencilla por tarea: un criterio por fila, con sus niveles guardados en JSON
create table if not exists planeacion_rubricas (
  id bigint generated by default as identity primary key,
  tarea_id bigint references planeacion_tareas(id) on delete cascade unique,
  criterios jsonb not null default '[]',
  actualizado_en timestamptz default now()
);

alter table planeacion_rubricas enable row level security;

drop policy if exists "planeacion_rubricas_select_todos" on planeacion_rubricas;
create policy "planeacion_rubricas_select_todos"
  on planeacion_rubricas for select using (true);

drop policy if exists "planeacion_rubricas_write_todos" on planeacion_rubricas;
create policy "planeacion_rubricas_write_todos"
  on planeacion_rubricas for all using (true) with check (true);

-- Estructura pedagógica más formal por clase (inicio/desarrollo/cierre)
alter table planeaciones add column if not exists momento_inicio text;
alter table planeaciones add column if not exists momento_desarrollo text;
alter table planeaciones add column if not exists momento_cierre text;
alter table planeaciones add column if not exists indicador_desempeno text;
alter table planeaciones add column if not exists duracion_minutos integer;

-- Catálogo propio de DBA y Competencias (el docente los va creando y reutilizando)
create table if not exists estandares (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  tipo text not null check (tipo in ('dba','competencia')),
  codigo text,
  descripcion text not null,
  area text,
  grado_id text,
  creado_en timestamptz default now()
);

alter table estandares enable row level security;

drop policy if exists "estandares_select_todos" on estandares;
create policy "estandares_select_todos"
  on estandares for select using (true);

drop policy if exists "estandares_write_todos" on estandares;
create policy "estandares_write_todos"
  on estandares for all using (true) with check (true);

-- Vínculo entre una unidad/clase y los DBA/competencias que trabaja
create table if not exists planeacion_estandares (
  id bigint generated by default as identity primary key,
  planeacion_id bigint references planeaciones(id) on delete cascade,
  estandar_id bigint references estandares(id) on delete cascade,
  unique (planeacion_id, estandar_id)
);

alter table planeacion_estandares enable row level security;

drop policy if exists "planeacion_estandares_select_todos" on planeacion_estandares;
create policy "planeacion_estandares_select_todos"
  on planeacion_estandares for select using (true);

drop policy if exists "planeacion_estandares_write_todos" on planeacion_estandares;
create policy "planeacion_estandares_write_todos"
  on planeacion_estandares for all using (true) with check (true);

-- Evaluaciones virtuales
create table if not exists evaluaciones (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete cascade,
  materia_id bigint references materias(id) on delete cascade,
  grado_id text,
  periodo text,
  planeacion_id bigint references planeaciones(id) on delete set null,
  titulo text not null,
  descripcion text,
  fecha_apertura date,
  fecha_cierre date,
  intentos_permitidos integer,
  tiempo_limite_minutos integer,
  estado text not null default 'borrador' check (estado in ('borrador','publicada')),
  creado_en timestamptz default now()
);

alter table evaluaciones enable row level security;
drop policy if exists "evaluaciones_select_todos" on evaluaciones;
create policy "evaluaciones_select_todos" on evaluaciones for select using (true);
drop policy if exists "evaluaciones_write_todos" on evaluaciones;
create policy "evaluaciones_write_todos" on evaluaciones for all using (true) with check (true);

create table if not exists evaluacion_preguntas (
  id bigint generated by default as identity primary key,
  evaluacion_id bigint references evaluaciones(id) on delete cascade,
  orden integer default 0,
  tipo text not null check (tipo in ('opcion_multiple','verdadero_falso','respuesta_corta')),
  enunciado text not null,
  puntos numeric not null default 1,
  opciones jsonb default '[]'
);

alter table evaluacion_preguntas enable row level security;
drop policy if exists "evaluacion_preguntas_select_todos" on evaluacion_preguntas;
create policy "evaluacion_preguntas_select_todos" on evaluacion_preguntas for select using (true);
drop policy if exists "evaluacion_preguntas_write_todos" on evaluacion_preguntas;
create policy "evaluacion_preguntas_write_todos" on evaluacion_preguntas for all using (true) with check (true);

create table if not exists evaluacion_intentos (
  id bigint generated by default as identity primary key,
  evaluacion_id bigint references evaluaciones(id) on delete cascade,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  numero_intento integer not null default 1,
  iniciado_en timestamptz default now(),
  entregado_en timestamptz,
  puntaje_obtenido numeric,
  puntaje_maximo numeric,
  estado text not null default 'en_progreso' check (estado in ('en_progreso','entregado','calificado')),
  visible_para_estudiante boolean not null default false
);

alter table evaluacion_intentos enable row level security;
drop policy if exists "evaluacion_intentos_select_todos" on evaluacion_intentos;
create policy "evaluacion_intentos_select_todos" on evaluacion_intentos for select using (true);
drop policy if exists "evaluacion_intentos_write_todos" on evaluacion_intentos;
create policy "evaluacion_intentos_write_todos" on evaluacion_intentos for all using (true) with check (true);

create table if not exists evaluacion_respuestas (
  id bigint generated by default as identity primary key,
  intento_id bigint references evaluacion_intentos(id) on delete cascade,
  pregunta_id bigint references evaluacion_preguntas(id) on delete cascade,
  respuesta text,
  correcta boolean,
  puntos_obtenidos numeric
);

alter table evaluacion_respuestas enable row level security;
drop policy if exists "evaluacion_respuestas_select_todos" on evaluacion_respuestas;
create policy "evaluacion_respuestas_select_todos" on evaluacion_respuestas for select using (true);
drop policy if exists "evaluacion_respuestas_write_todos" on evaluacion_respuestas;
create policy "evaluacion_respuestas_write_todos" on evaluacion_respuestas for all using (true) with check (true);

-- Le entrega al estudiante las preguntas SIN revelar cuál opción es la correcta
create or replace function obtener_preguntas_evaluacion(p_evaluacion_id bigint)
returns table (id bigint, orden integer, tipo text, enunciado text, puntos numeric, opciones jsonb)
language sql
security definer
as $$
  select p.id, p.orden, p.tipo, p.enunciado, p.puntos,
    case when p.tipo = 'respuesta_corta' then '[]'::jsonb
    else (select coalesce(jsonb_agg(jsonb_build_object('texto', opt->>'texto')), '[]'::jsonb) from jsonb_array_elements(p.opciones) opt)
    end as opciones
  from evaluacion_preguntas p
  where p.evaluacion_id = p_evaluacion_id
  order by p.orden;
$$;

-- Abre un intento nuevo, respetando el límite de intentos permitidos
create or replace function iniciar_intento_evaluacion(p_evaluacion_id bigint, p_estudiante_id bigint)
returns bigint
language plpgsql
security definer
as $$
declare
  v_intentos_permitidos integer;
  v_usados integer;
  v_nuevo_id bigint;
  v_numero integer;
begin
  select intentos_permitidos into v_intentos_permitidos from evaluaciones where id = p_evaluacion_id;
  select count(*) into v_usados from evaluacion_intentos where evaluacion_id = p_evaluacion_id and estudiante_id = p_estudiante_id;
  if v_intentos_permitidos is not null and v_usados >= v_intentos_permitidos then
    raise exception 'Ya usaste todos los intentos permitidos para esta evaluación.';
  end if;
  v_numero := v_usados + 1;
  insert into evaluacion_intentos (evaluacion_id, estudiante_id, numero_intento, estado)
  values (p_evaluacion_id, p_estudiante_id, v_numero, 'en_progreso')
  returning id into v_nuevo_id;
  return v_nuevo_id;
end;
$$;

-- Recibe las respuestas del estudiante y califica del lado del servidor
-- (la respuesta correcta nunca viaja al navegador del estudiante)
create or replace function entregar_intento_evaluacion(p_intento_id bigint, p_respuestas jsonb)
returns void
language plpgsql
security definer
as $$
declare
  r jsonb;
  v_pregunta record;
  v_correcta boolean;
  v_puntos numeric;
  v_total numeric := 0;
  v_maximo numeric := 0;
begin
  for r in select * from jsonb_array_elements(p_respuestas)
  loop
    select * into v_pregunta from evaluacion_preguntas where id = (r->>'pregunta_id')::bigint;
    v_maximo := v_maximo + v_pregunta.puntos;

    if v_pregunta.tipo = 'respuesta_corta' then
      insert into evaluacion_respuestas (intento_id, pregunta_id, respuesta, correcta, puntos_obtenidos)
      values (p_intento_id, v_pregunta.id, r->>'respuesta', null, null);
    else
      select coalesce(bool_or((opt->>'correcta')::boolean), false) into v_correcta
      from jsonb_array_elements(v_pregunta.opciones) opt
      where opt->>'texto' = (r->>'respuesta');
      v_puntos := case when v_correcta then v_pregunta.puntos else 0 end;
      v_total := v_total + coalesce(v_puntos, 0);
      insert into evaluacion_respuestas (intento_id, pregunta_id, respuesta, correcta, puntos_obtenidos)
      values (p_intento_id, v_pregunta.id, r->>'respuesta', v_correcta, v_puntos);
    end if;
  end loop;

  update evaluacion_intentos
  set entregado_en = now(), estado = 'entregado', puntaje_obtenido = v_total, puntaje_maximo = v_maximo
  where id = p_intento_id;
end;
$$;

-- Comentarios generales según la banda de desempeño (Bajo/Básico/Alto/Superior),
-- reutilizables en todas las materias — se muestran junto a la nota del estudiante.
create table if not exists comentarios_desempeno (
  banda text primary key check (banda in ('bajo','basico','alto','superior')),
  comentario text not null,
  actualizado_en timestamptz default now()
);

alter table comentarios_desempeno enable row level security;
drop policy if exists "comentarios_desempeno_select_todos" on comentarios_desempeno;
create policy "comentarios_desempeno_select_todos" on comentarios_desempeno for select using (true);
drop policy if exists "comentarios_desempeno_write_todos" on comentarios_desempeno;
create policy "comentarios_desempeno_write_todos" on comentarios_desempeno for all using (true) with check (true);

insert into comentarios_desempeno (banda, comentario) values
  ('bajo', 'Es necesario reforzar los temas trabajados este periodo. Te recomendamos buscar apoyo adicional con tu docente.'),
  ('basico', 'Vas cumpliendo con lo mínimo esperado. Con un poco más de dedicación puedes mejorar bastante.'),
  ('alto', 'Buen desempeño este periodo. Sigue trabajando con la misma constancia.'),
  ('superior', '¡Excelente desempeño! Continúa así, tu esfuerzo se nota.')
on conflict (banda) do nothing;

-- Asegura que el portal del estudiante (que entra sin sesión de docente) pueda
-- leer sus propias notas. Si estas tablas son de antes de esta conversación y
-- nunca tuvieron una política pública, esto la agrega sin tocar nada más.
alter table notas_finales_periodo enable row level security;
drop policy if exists "notas_finales_periodo_select_todos" on notas_finales_periodo;
create policy "notas_finales_periodo_select_todos" on notas_finales_periodo for select using (true);

alter table notas_valores enable row level security;
drop policy if exists "notas_valores_select_todos" on notas_valores;
create policy "notas_valores_select_todos" on notas_valores for select using (true);

alter table notas_actividades enable row level security;
drop policy if exists "notas_actividades_select_todos" on notas_actividades;
create policy "notas_actividades_select_todos" on notas_actividades for select using (true);

alter table notas_categorias enable row level security;
drop policy if exists "notas_categorias_select_todos" on notas_categorias;
create policy "notas_categorias_select_todos" on notas_categorias for select using (true);

alter table materias enable row level security;
drop policy if exists "materias_select_todos" on materias;
create policy "materias_select_todos" on materias for select using (true);

-- Periodo vigente por materia: para que la app arranque ahí en vez de siempre en Periodo 1
alter table notas_config add column if not exists periodo_actual text default '1';

-- Las "clases" (a diferencia de las "unidades") no necesitan periodo propio —
-- lo heredan de la unidad a la que pertenecen.
alter table planeaciones alter column periodo drop not null;

-- Estructura de secuencia didáctica (Díaz-Barriga, UNAM): problema/proyecto y
-- orientaciones de evaluación a nivel de unidad
alter table planeaciones add column if not exists problema_proyecto text;
alter table planeaciones add column if not exists orientaciones_evaluacion text;

-- Control de dictado: la misma clase planeada se puede registrar como dictada
-- (o pendiente) en varios cursos distintos, cada uno con su propia fecha.
create table if not exists planeacion_dictados (
  id bigint generated by default as identity primary key,
  clase_id bigint references planeaciones(id) on delete cascade,
  grado_id text not null,
  fecha date,
  estado text not null default 'pendiente' check (estado in ('pendiente','dictada','aplazada')),
  observacion text,
  creado_en timestamptz default now()
);

alter table planeacion_dictados enable row level security;
drop policy if exists "planeacion_dictados_select_todos" on planeacion_dictados;
create policy "planeacion_dictados_select_todos" on planeacion_dictados for select using (true);
drop policy if exists "planeacion_dictados_write_todos" on planeacion_dictados;
create policy "planeacion_dictados_write_todos" on planeacion_dictados for all using (true) with check (true);

-- Banco de premios: catálogo de premios que se canjean con monedas
create table if not exists banco_premios (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  nombre text not null,
  descripcion text,
  emoji text,
  costo_monedas integer not null default 10,
  peso integer not null default 1,
  stock integer,
  activo boolean not null default true,
  creado_en timestamptz default now()
);

alter table banco_premios enable row level security;
drop policy if exists "banco_premios_select_todos" on banco_premios;
create policy "banco_premios_select_todos" on banco_premios for select using (true);
drop policy if exists "banco_premios_write_todos" on banco_premios;
create policy "banco_premios_write_todos" on banco_premios for all using (true) with check (true);

-- Canjes: registro de qué le tocó a cada estudiante y si ya se le entregó
create table if not exists banco_canjes (
  id bigint generated by default as identity primary key,
  premio_id bigint references banco_premios(id) on delete set null,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  costo_pagado integer not null,
  estado text not null default 'pendiente' check (estado in ('pendiente','entregado')),
  fecha timestamptz default now()
);

alter table banco_canjes enable row level security;
drop policy if exists "banco_canjes_select_todos" on banco_canjes;
create policy "banco_canjes_select_todos" on banco_canjes for select using (true);
drop policy if exists "banco_canjes_write_todos" on banco_canjes;
create policy "banco_canjes_write_todos" on banco_canjes for all using (true) with check (true);

-- Proyectos y Forja: tareas calificables que el docente asigna directo (sin pasar
-- por Planeaciones), y cuya nota se manda sola a la Planilla de Calificaciones.
create table if not exists tareas_calificables (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete cascade,
  materia_id bigint references materias(id) on delete cascade,
  grado_id text not null,
  periodo text not null,
  categoria_id bigint references notas_categorias(id) on delete set null,
  tipo text not null check (tipo in ('proyecto','forja')),
  titulo text not null,
  descripcion text,
  fecha_entrega date,
  rubrica jsonb default '[]',
  creado_en timestamptz default now()
);

alter table tareas_calificables enable row level security;
drop policy if exists "tareas_calificables_select_todos" on tareas_calificables;
create policy "tareas_calificables_select_todos" on tareas_calificables for select using (true);
drop policy if exists "tareas_calificables_write_todos" on tareas_calificables;
create policy "tareas_calificables_write_todos" on tareas_calificables for all using (true) with check (true);

create table if not exists tarea_entregas (
  id bigint generated by default as identity primary key,
  tarea_id bigint references tareas_calificables(id) on delete cascade,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  estado text not null default 'pendiente' check (estado in ('pendiente','entregado','calificado')),
  nota numeric,
  comentario text,
  fecha_entrega timestamptz,
  fecha_calificacion timestamptz,
  unique (tarea_id, estudiante_id)
);

alter table tarea_entregas enable row level security;
drop policy if exists "tarea_entregas_select_todos" on tarea_entregas;
create policy "tarea_entregas_select_todos" on tarea_entregas for select using (true);
drop policy if exists "tarea_entregas_write_todos" on tarea_entregas;
create policy "tarea_entregas_write_todos" on tarea_entregas for all using (true) with check (true);

-- Imagen del menú lateral, independiente del logo de la institución (usado en actas)
alter table institucion add column if not exists imagen_menu_url text;

-- Color configurable por grado, reutilizado en el calendario de Horario y en
-- cualquier otro lugar que muestre grados con color (se actualiza en un solo lugar)
alter table grados add column if not exists color text;

-- ============================================================
-- Privacidad por docente: Materias y Calificaciones
-- Cada docente ve/edita solo SUS materias y notas. El portal del
-- estudiante (sin sesión, rol "anon") sigue pudiendo leer todo,
-- para consultar sus propias notas sin importar quién las creó.
-- Actas, Estudiantes, Reinos, Evaluaciones, Planeaciones, etc.
-- NO se tocan — siguen compartidos como hasta ahora.
-- ============================================================

-- MATERIAS
drop policy if exists "materias_select_todos" on materias;
drop policy if exists "materias_select_propio_o_publico" on materias;
create policy "materias_select_propio_o_publico" on materias for select
  using (auth.role() = 'anon' or auth.uid() = docente_id or docente_id is null);

drop policy if exists "materias_insert_propio" on materias;
create policy "materias_insert_propio" on materias for insert
  with check (auth.uid() = docente_id);

drop policy if exists "materias_update_propio" on materias;
create policy "materias_update_propio" on materias for update
  using (auth.uid() = docente_id or docente_id is null);

drop policy if exists "materias_delete_propio" on materias;
create policy "materias_delete_propio" on materias for delete
  using (auth.uid() = docente_id or docente_id is null);

-- NOTAS_CATEGORIAS (por materia_id)
drop policy if exists "notas_categorias_select_todos" on notas_categorias;
drop policy if exists "notas_categorias_select_propio_o_publico" on notas_categorias;
create policy "notas_categorias_select_propio_o_publico" on notas_categorias for select
  using (
    auth.role() = 'anon'
    or exists (select 1 from materias m where m.id = notas_categorias.materia_id and (m.docente_id = auth.uid() or m.docente_id is null))
  );

drop policy if exists "notas_categorias_write_propio" on notas_categorias;
create policy "notas_categorias_write_propio" on notas_categorias for all
  using (exists (select 1 from materias m where m.id = notas_categorias.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)))
  with check (exists (select 1 from materias m where m.id = notas_categorias.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)));

-- NOTAS_ACTIVIDADES (por materia_id)
drop policy if exists "notas_actividades_select_todos" on notas_actividades;
drop policy if exists "notas_actividades_select_propio_o_publico" on notas_actividades;
create policy "notas_actividades_select_propio_o_publico" on notas_actividades for select
  using (
    auth.role() = 'anon'
    or exists (select 1 from materias m where m.id = notas_actividades.materia_id and (m.docente_id = auth.uid() or m.docente_id is null))
  );

drop policy if exists "notas_actividades_write_propio" on notas_actividades;
create policy "notas_actividades_write_propio" on notas_actividades for all
  using (exists (select 1 from materias m where m.id = notas_actividades.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)))
  with check (exists (select 1 from materias m where m.id = notas_actividades.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)));

-- NOTAS_VALORES (por actividad_id -> materia_id)
drop policy if exists "notas_valores_select_todos" on notas_valores;
drop policy if exists "notas_valores_select_propio_o_publico" on notas_valores;
create policy "notas_valores_select_propio_o_publico" on notas_valores for select
  using (
    auth.role() = 'anon'
    or exists (
      select 1 from notas_actividades a join materias m on m.id = a.materia_id
      where a.id = notas_valores.actividad_id and (m.docente_id = auth.uid() or m.docente_id is null)
    )
  );

drop policy if exists "notas_valores_write_propio" on notas_valores;
create policy "notas_valores_write_propio" on notas_valores for all
  using (
    exists (
      select 1 from notas_actividades a join materias m on m.id = a.materia_id
      where a.id = notas_valores.actividad_id and (m.docente_id = auth.uid() or m.docente_id is null)
    )
  )
  with check (
    exists (
      select 1 from notas_actividades a join materias m on m.id = a.materia_id
      where a.id = notas_valores.actividad_id and (m.docente_id = auth.uid() or m.docente_id is null)
    )
  );

-- NOTAS_FINALES_PERIODO (por materia_id)
drop policy if exists "notas_finales_periodo_select_todos" on notas_finales_periodo;
drop policy if exists "notas_finales_periodo_select_propio_o_publico" on notas_finales_periodo;
create policy "notas_finales_periodo_select_propio_o_publico" on notas_finales_periodo for select
  using (
    auth.role() = 'anon'
    or exists (select 1 from materias m where m.id = notas_finales_periodo.materia_id and (m.docente_id = auth.uid() or m.docente_id is null))
  );

drop policy if exists "notas_finales_periodo_write_propio" on notas_finales_periodo;
create policy "notas_finales_periodo_write_propio" on notas_finales_periodo for all
  using (exists (select 1 from materias m where m.id = notas_finales_periodo.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)))
  with check (exists (select 1 from materias m where m.id = notas_finales_periodo.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)));

-- NOTAS_CONFIG (por materia_id) — no la necesita el estudiante, solo el docente dueño
alter table notas_config enable row level security;
drop policy if exists "notas_config_select_propio" on notas_config;
create policy "notas_config_select_propio" on notas_config for select
  using (exists (select 1 from materias m where m.id = notas_config.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)));

drop policy if exists "notas_config_write_propio" on notas_config;
create policy "notas_config_write_propio" on notas_config for all
  using (exists (select 1 from materias m where m.id = notas_config.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)))
  with check (exists (select 1 from materias m where m.id = notas_config.materia_id and (m.docente_id = auth.uid() or m.docente_id is null)));

-- ============================================================
-- Ampliación de privacidad: eliminar estudiantes (solo admins),
-- dar/quitar monedas (solo a quien le dictás), y Banco de premios
-- (cada docente edita solo los que creó).
-- ============================================================

-- Función auxiliar: ¿este docente le dicta clase a este grado?
-- Revisa Horario, Materias/Notas, Evaluaciones, Proyectos/Forja y Planeaciones.
create or replace function docente_dicta_grado(p_docente uuid, p_grado text)
returns boolean
language sql
stable
as $$
  select
    exists (select 1 from horario h where h.docente_id = p_docente and h.grado_id = p_grado)
    or exists (select 1 from notas_actividades a join materias m on m.id = a.materia_id where m.docente_id = p_docente and a.grado_id = p_grado)
    or exists (select 1 from evaluaciones e where e.docente_id = p_docente and e.grado_id = p_grado)
    or exists (select 1 from tareas_calificables t where t.docente_id = p_docente and t.grado_id = p_grado)
    or exists (select 1 from planeaciones pl where pl.docente_id = p_docente and pl.grado_id = p_grado and pl.tipo = 'unidad');
$$;

-- PROGRESO (xp/vida/monedas del estudiante): un docente solo puede darle o
-- quitarle monedas/xp a estudiantes de los grados que le dicta. El estudiante
-- (portal sin sesión, rol "anon") sigue pudiendo canjear sus propias monedas
-- en el Banco sin restricción, porque eso no lo hace un docente.
alter table progreso enable row level security;

drop policy if exists "progreso_select_todos" on progreso;
create policy "progreso_select_todos" on progreso for select using (true);

drop policy if exists "progreso_write_anon_o_docente_grado" on progreso;
create policy "progreso_write_anon_o_docente_grado" on progreso for all
  using (
    auth.role() = 'anon'
    or exists (select 1 from estudiantes e where e.id = progreso.estudiante_id and docente_dicta_grado(auth.uid(), e.grado_id))
  )
  with check (
    auth.role() = 'anon'
    or exists (select 1 from estudiantes e where e.id = progreso.estudiante_id and docente_dicta_grado(auth.uid(), e.grado_id))
  );

-- BANCO DE PREMIOS: cualquiera puede seguir viendo el catálogo, pero cada
-- docente solo puede crear/editar/eliminar los premios que él mismo creó.
drop policy if exists "banco_premios_write_todos" on banco_premios;
drop policy if exists "banco_premios_insert_propio" on banco_premios;
create policy "banco_premios_insert_propio" on banco_premios for insert
  with check (auth.uid() = docente_id);
drop policy if exists "banco_premios_update_propio" on banco_premios;
create policy "banco_premios_update_propio" on banco_premios for update
  using (auth.uid() = docente_id or docente_id is null);
drop policy if exists "banco_premios_delete_propio" on banco_premios;
create policy "banco_premios_delete_propio" on banco_premios for delete
  using (auth.uid() = docente_id or docente_id is null);

-- ESTUDIANTES: eliminar (desactivar) un estudiante queda reservado a
-- administradores. El resto de las ediciones (nombre, reino, documento,
-- inclusión, traslado, etc.) sigue abierto a cualquier docente, como hasta ahora.
create or replace function proteger_desactivar_estudiante()
returns trigger
language plpgsql
security definer
as $$
begin
  if OLD.activo is distinct from NEW.activo then
    if not exists (select 1 from profesores p where p.id = auth.uid() and p.es_admin = true) then
      raise exception 'Solo un administrador puede eliminar estudiantes.';
    end if;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_proteger_desactivar_estudiante on estudiantes;
create trigger trg_proteger_desactivar_estudiante
  before update on estudiantes
  for each row
  execute function proteger_desactivar_estudiante();

-- Asegura que la tabla acudientes tenga TODAS las columnas que usa la app
-- (por si se creó en algún momento con una versión distinta/incompleta)
alter table acudientes add column if not exists nombre_padre text;
alter table acudientes add column if not exists telefono_padre text;
alter table acudientes add column if not exists nombre_madre text;
alter table acudientes add column if not exists telefono_madre text;
alter table acudientes add column if not exists contacto_emergencia_nombre text;
alter table acudientes add column if not exists contacto_emergencia_telefono text;
alter table acudientes add column if not exists contacto_emergencia_relacion text;
alter table acudientes add column if not exists direccion text;

-- Asegura que acudientes tenga una sola fila por estudiante (necesario para
-- que "guardar acudiente" sepa si crear una fila nueva o actualizar la existente)
alter table acudientes drop constraint if exists acudientes_estudiante_id_key;
alter table acudientes add constraint acudientes_estudiante_id_key unique (estudiante_id);

-- ============================================================
-- PIAR completo (Plan Individual de Ajustes Razonables)
-- Adaptado a las tablas reales (estudiantes, profesores).
-- Reutiliza estudiantes.piar (ya existente) para marcar quién tiene proceso.
-- Modelo abierto entre docentes, igual que el resto de la app.
-- ============================================================

-- Formulario PIAR (uno o varios por estudiante — se puede revisar/actualizar)
create table if not exists piar_formularios (
  id bigint generated by default as identity primary key,
  estudiante_id bigint not null references estudiantes(id) on delete cascade,
  fecha_diligenciamiento date,
  lugar_diligenciamiento text,
  institucion_educativa text,
  diligenciado_por uuid references auth.users(id),
  fecha_valoracion_pedagogica date,
  profesionales_valoracion text,
  creado_en timestamptz default now()
);

alter table piar_formularios enable row level security;
drop policy if exists "piar_formularios_select_todos" on piar_formularios;
create policy "piar_formularios_select_todos" on piar_formularios for select using (true);
drop policy if exists "piar_formularios_write_todos" on piar_formularios;
create policy "piar_formularios_write_todos" on piar_formularios for all using (true) with check (true);

-- Datos sensibles (salud + hogar) — tabla separada a propósito, como en el diseño original
create table if not exists piar_datos_sensibles (
  id bigint generated by default as identity primary key,
  piar_formulario_id bigint not null unique references piar_formularios(id) on delete cascade,
  afiliacion_salud text,
  diagnostico_medico text,
  atencion_medica text,
  medicamentos text,
  apoyos_tecnicos text,
  nombre_madre text,
  nombre_padre text,
  nombre_cuidador text,
  ocupacion_madre text,
  ocupacion_padre text,
  redes_apoyo text,
  otras_observaciones text,
  creado_en timestamptz default now()
);

alter table piar_datos_sensibles enable row level security;
drop policy if exists "piar_datos_sensibles_select_todos" on piar_datos_sensibles;
create policy "piar_datos_sensibles_select_todos" on piar_datos_sensibles for select using (true);
drop policy if exists "piar_datos_sensibles_write_todos" on piar_datos_sensibles;
create policy "piar_datos_sensibles_write_todos" on piar_datos_sensibles for all using (true) with check (true);

-- Ajustes razonables (lo que realmente usan los docentes en el día a día)
create table if not exists piar_ajustes (
  id bigint generated by default as identity primary key,
  piar_formulario_id bigint not null references piar_formularios(id) on delete cascade,
  area_asignatura text,
  objetivo text,
  barrera_identificada text,
  descripcion_ajuste text,
  tipo_apoyo text,
  indicador_seguimiento text,
  creado_en timestamptz default now()
);

alter table piar_ajustes enable row level security;
drop policy if exists "piar_ajustes_select_todos" on piar_ajustes;
create policy "piar_ajustes_select_todos" on piar_ajustes for select using (true);
drop policy if exists "piar_ajustes_write_todos" on piar_ajustes;
create policy "piar_ajustes_write_todos" on piar_ajustes for all using (true) with check (true);

-- Seguimiento de cada ajuste (notas rápidas del docente: funcionó / no funcionó / observación)
create table if not exists piar_seguimiento (
  id bigint generated by default as identity primary key,
  piar_ajuste_id bigint not null references piar_ajustes(id) on delete cascade,
  autor_id uuid references auth.users(id),
  fecha date default current_date,
  periodo_academico text,
  nota text not null,
  requiere_modificacion boolean default false,
  creado_en timestamptz default now()
);

alter table piar_seguimiento enable row level security;
drop policy if exists "piar_seguimiento_select_todos" on piar_seguimiento;
create policy "piar_seguimiento_select_todos" on piar_seguimiento for select using (true);
drop policy if exists "piar_seguimiento_write_todos" on piar_seguimiento;
create policy "piar_seguimiento_write_todos" on piar_seguimiento for all using (true) with check (true);

-- Permite que las Misiones (Evaluaciones) también manden la nota, ya escalada,
-- directo a la Planilla de Calificaciones cuando se publica el resultado.
alter table evaluaciones add column if not exists categoria_id bigint references notas_categorias(id);

-- Indicaciones como lista (viñetas) en vez de un solo bloque de texto,
-- para mostrarlas mejor formateadas al estudiante.
alter table evaluaciones add column if not exists indicaciones jsonb default '[]';

-- Permite combinar más de una materia en la misma unidad/clase (ej: clases
-- integradas de Ética + Religión en el mismo bloque).
alter table planeaciones add column if not exists materias_extra integer[] default '{}';

-- ============================================================
-- Álbum de criaturas coleccionables — sobres comprados con monedas
-- ============================================================

create table if not exists criaturas (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  nombre text not null,
  emoji text not null default '✨',
  rareza text not null default 'comun' check (rareza in ('comun','rara','epica','legendaria')),
  descripcion text,
  peso integer not null default 10,
  activo boolean not null default true,
  creado_en timestamptz default now()
);

alter table criaturas enable row level security;
drop policy if exists "criaturas_select_todos" on criaturas;
create policy "criaturas_select_todos" on criaturas for select using (true);
drop policy if exists "criaturas_write_todos" on criaturas;
create policy "criaturas_write_todos" on criaturas for all using (true) with check (true);

create table if not exists estudiante_criaturas (
  id bigint generated by default as identity primary key,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  criatura_id bigint references criaturas(id) on delete cascade,
  cantidad integer not null default 1,
  obtenida_en timestamptz default now(),
  unique (estudiante_id, criatura_id)
);

alter table estudiante_criaturas enable row level security;
drop policy if exists "estudiante_criaturas_select_todos" on estudiante_criaturas;
create policy "estudiante_criaturas_select_todos" on estudiante_criaturas for select using (true);
drop policy if exists "estudiante_criaturas_write_todos" on estudiante_criaturas;
create policy "estudiante_criaturas_write_todos" on estudiante_criaturas for all using (true) with check (true);

create table if not exists album_config (
  id integer primary key default 1,
  costo_sobre integer not null default 15,
  cartas_por_sobre integer not null default 3,
  nombre_album text not null default 'Álbum de Criaturas del Códice'
);
insert into album_config (id) values (1) on conflict (id) do nothing;

alter table album_config enable row level security;
drop policy if exists "album_config_select_todos" on album_config;
create policy "album_config_select_todos" on album_config for select using (true);
drop policy if exists "album_config_write_todos" on album_config;
create policy "album_config_write_todos" on album_config for all using (true) with check (true);

-- Catálogo inicial de ejemplo (editable después desde la app)
insert into criaturas (nombre, emoji, rareza, descripcion, peso) values
  ('Chispilla', '🐿️', 'comun', 'Una criatura curiosa que guarda chispas de conocimiento en sus mejillas.', 30),
  ('Hojarín', '🍃', 'comun', 'Vive entre las páginas viejas de la biblioteca del Códice.', 30),
  ('Burbujeo', '💧', 'comun', 'Aparece cuando alguien resuelve un problema difícil.', 30),
  ('Rocalta', '🪨', 'rara', 'Una criatura testaruda que nunca abandona una tarea a medias.', 15),
  ('Plumazo', '🪶', 'rara', 'Vuela más rápido cuando alguien levanta la mano para participar.', 15),
  ('Flamito', '🔥', 'rara', 'Se enciende con el entusiasmo de la clase.', 15),
  ('Tormentia', '⚡', 'epica', 'Solo aparece en las tormentas de ideas más brillantes.', 6),
  ('Lunárion', '🌙', 'epica', 'Guardián nocturno de los estudiantes más dedicados.', 6),
  ('Cristalum', '💎', 'legendaria', 'Se dice que nace de un cristal de experiencia perfecto. Muy escaso.', 2),
  ('Códexis', '📖', 'legendaria', 'El guardián original del Códice. Casi nadie lo ha visto.', 1)
on conflict do nothing;

-- Formato de carta de juego para las criaturas del Álbum
alter table criaturas add column if not exists imagen_url text;
alter table criaturas add column if not exists poder integer default 0;
alter table criaturas add column if not exists vida integer default 0;
alter table criaturas add column if not exists experiencia integer default 0;
alter table criaturas add column if not exists oro integer default 0;

-- ============================================================
-- Códice personal del estudiante: diario de reflexiones y
-- aprendizajes, con posibilidad de que el docente comente cada entrada.
-- ============================================================
create table if not exists codice_entradas (
  id bigint generated by default as identity primary key,
  estudiante_id bigint not null references estudiantes(id) on delete cascade,
  materia_id bigint references materias(id) on delete set null,
  titulo text,
  contenido text not null,
  fecha date not null default current_date,
  creado_en timestamptz default now()
);

alter table codice_entradas enable row level security;
drop policy if exists "codice_entradas_select_todos" on codice_entradas;
create policy "codice_entradas_select_todos" on codice_entradas for select using (true);
drop policy if exists "codice_entradas_write_todos" on codice_entradas;
create policy "codice_entradas_write_todos" on codice_entradas for all using (true) with check (true);

create table if not exists codice_comentarios (
  id bigint generated by default as identity primary key,
  entrada_id bigint not null references codice_entradas(id) on delete cascade,
  autor_id uuid references auth.users(id),
  comentario text not null,
  creado_en timestamptz default now()
);

alter table codice_comentarios enable row level security;
drop policy if exists "codice_comentarios_select_todos" on codice_comentarios;
create policy "codice_comentarios_select_todos" on codice_comentarios for select using (true);
drop policy if exists "codice_comentarios_write_todos" on codice_comentarios;
create policy "codice_comentarios_write_todos" on codice_comentarios for all using (true) with check (true);

-- Valor de la semana: se actualiza semanalmente desde la portada (Inicio),
-- con imagen propia. Una sola fila que se va sobrescribiendo cada semana.
create table if not exists valor_semanal (
  id integer primary key default 1,
  nombre text,
  descripcion text,
  imagen_url text,
  actualizado_en timestamptz default now()
);
insert into valor_semanal (id) values (1) on conflict (id) do nothing;

alter table valor_semanal enable row level security;
drop policy if exists "valor_semanal_select_todos" on valor_semanal;
create policy "valor_semanal_select_todos" on valor_semanal for select using (true);
drop policy if exists "valor_semanal_write_todos" on valor_semanal;
create policy "valor_semanal_write_todos" on valor_semanal for all using (true) with check (true);

-- Enlace externo opcional en Proyectos/Forja (formulario, material, actividad, etc.)
alter table tareas_calificables add column if not exists url text;

-- Alternativa al archivo subido: pegar código HTML (ej: <img src="...">) para
-- usar una imagen alojada externamente, sin el límite de tamaño del archivo.
alter table valor_semanal add column if not exists html_contenido text;

-- ============================================================
-- Anuncios / tablero de mensajes para los estudiantes
-- ============================================================
create table if not exists anuncios (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  grado_id text, -- null = para todos los grados
  titulo text not null,
  contenido text not null,
  fijado boolean not null default false,
  creado_en timestamptz default now()
);

alter table anuncios enable row level security;
drop policy if exists "anuncios_select_todos" on anuncios;
create policy "anuncios_select_todos" on anuncios for select using (true);
drop policy if exists "anuncios_write_todos" on anuncios;
create policy "anuncios_write_todos" on anuncios for all using (true) with check (true);

-- Notificación de reflexiones nuevas + calificación del Códice
alter table codice_entradas add column if not exists revisado boolean not null default false;
alter table codice_entradas add column if not exists nota numeric;
alter table codice_entradas add column if not exists categoria_id bigint references notas_categorias(id);

-- ============================================================
-- Insignias / logros automáticos — se desbloquean solos al
-- cumplir un hito (nivel, monedas, álbum completo, etc.)
-- ============================================================
create table if not exists logros_catalogo (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  nombre text not null,
  descripcion text,
  emoji text not null default '🏅',
  tipo text not null check (tipo in ('nivel_xp','monedas','coleccion_completa','codice_entradas','evaluaciones_completadas','asistencia_presentes')),
  umbral integer default 0, -- no se usa para 'coleccion_completa'
  activo boolean not null default true,
  creado_en timestamptz default now()
);

alter table logros_catalogo enable row level security;
drop policy if exists "logros_catalogo_select_todos" on logros_catalogo;
create policy "logros_catalogo_select_todos" on logros_catalogo for select using (true);
drop policy if exists "logros_catalogo_write_todos" on logros_catalogo;
create policy "logros_catalogo_write_todos" on logros_catalogo for all using (true) with check (true);

create table if not exists estudiante_logros (
  id bigint generated by default as identity primary key,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  logro_id bigint references logros_catalogo(id) on delete cascade,
  desbloqueado_en timestamptz default now(),
  unique (estudiante_id, logro_id)
);

alter table estudiante_logros enable row level security;
drop policy if exists "estudiante_logros_select_todos" on estudiante_logros;
create policy "estudiante_logros_select_todos" on estudiante_logros for select using (true);
drop policy if exists "estudiante_logros_write_todos" on estudiante_logros;
create policy "estudiante_logros_write_todos" on estudiante_logros for all using (true) with check (true);

-- Catálogo inicial de ejemplo (editable después desde la app)
insert into logros_catalogo (nombre, descripcion, emoji, tipo, umbral) values
  ('Primeros pasos', 'Alcanzaste el nivel Aprendiz', '🌱', 'nivel_xp', 1),
  ('Explorador del Códice', 'Llegaste a 100 XP', '🧭', 'nivel_xp', 100),
  ('Guardián del Saber', 'Llegaste a 300 XP', '🛡️', 'nivel_xp', 300),
  ('Leyenda del Códice', 'Llegaste a 600 XP', '👑', 'nivel_xp', 600),
  ('Bolsillos llenos', 'Juntaste 50 monedas', '🪙', 'monedas', 50),
  ('Pequeño tesoro', 'Juntaste 150 monedas', '💰', 'monedas', 150),
  ('Coleccionista completo', 'Conseguiste todas las criaturas del álbum', '🎴', 'coleccion_completa', 0),
  ('Voz reflexiva', 'Escribiste 5 entradas en tu Códice', '📖', 'codice_entradas', 5),
  ('Pensador constante', 'Escribiste 15 entradas en tu Códice', '✍️', 'codice_entradas', 15),
  ('Guerrero de misiones', 'Completaste 5 evaluaciones', '⚔️', 'evaluaciones_completadas', 5),
  ('Presente y constante', 'Acumulaste 20 asistencias', '🎯', 'asistencia_presentes', 20)
on conflict do nothing;

-- ============================================================
-- 1) Desafíos de equipo entre Reinos
-- ============================================================
create table if not exists desafios_reino (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  grado_id text not null,
  titulo text not null,
  descripcion text,
  tipo text not null default 'xp' check (tipo in ('xp','monedas')),
  meta integer not null default 100,
  fecha_inicio date not null default current_date,
  fecha_fin date,
  activo boolean not null default true,
  creado_en timestamptz default now()
);
alter table desafios_reino enable row level security;
drop policy if exists "desafios_reino_select_todos" on desafios_reino;
create policy "desafios_reino_select_todos" on desafios_reino for select using (true);
drop policy if exists "desafios_reino_write_todos" on desafios_reino;
create policy "desafios_reino_write_todos" on desafios_reino for all using (true) with check (true);

create table if not exists desafio_snapshots (
  id bigint generated by default as identity primary key,
  desafio_id bigint references desafios_reino(id) on delete cascade,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  valor_inicial integer not null default 0,
  unique (desafio_id, estudiante_id)
);
alter table desafio_snapshots enable row level security;
drop policy if exists "desafio_snapshots_select_todos" on desafio_snapshots;
create policy "desafio_snapshots_select_todos" on desafio_snapshots for select using (true);
drop policy if exists "desafio_snapshots_write_todos" on desafio_snapshots;
create policy "desafio_snapshots_write_todos" on desafio_snapshots for all using (true) with check (true);

-- ============================================================
-- 2) Misiones diarias/semanales
-- ============================================================
create table if not exists micro_misiones (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  titulo text not null,
  descripcion text,
  tipo text not null default 'diaria' check (tipo in ('diaria','semanal')),
  recompensa_monedas integer not null default 0,
  recompensa_xp integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz default now()
);
alter table micro_misiones enable row level security;
drop policy if exists "micro_misiones_select_todos" on micro_misiones;
create policy "micro_misiones_select_todos" on micro_misiones for select using (true);
drop policy if exists "micro_misiones_write_todos" on micro_misiones;
create policy "micro_misiones_write_todos" on micro_misiones for all using (true) with check (true);

create table if not exists micro_mision_completadas (
  id bigint generated by default as identity primary key,
  mision_id bigint references micro_misiones(id) on delete cascade,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  periodo_clave text not null, -- 'YYYY-MM-DD' para diarias, 'YYYY-WW' para semanales
  completado_en timestamptz default now(),
  unique (mision_id, estudiante_id, periodo_clave)
);
alter table micro_mision_completadas enable row level security;
drop policy if exists "micro_mision_completadas_select_todos" on micro_mision_completadas;
create policy "micro_mision_completadas_select_todos" on micro_mision_completadas for select using (true);
drop policy if exists "micro_mision_completadas_write_todos" on micro_mision_completadas;
create policy "micro_mision_completadas_write_todos" on micro_mision_completadas for all using (true) with check (true);

-- ============================================================
-- 3) Personalización cosmética con monedas
-- ============================================================
create table if not exists cosmeticos_catalogo (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  nombre text not null,
  tipo text not null check (tipo in ('marco','titulo')),
  valor text not null, -- color css para 'marco', texto para 'titulo'
  costo_monedas integer not null default 20,
  activo boolean not null default true,
  creado_en timestamptz default now()
);
alter table cosmeticos_catalogo enable row level security;
drop policy if exists "cosmeticos_catalogo_select_todos" on cosmeticos_catalogo;
create policy "cosmeticos_catalogo_select_todos" on cosmeticos_catalogo for select using (true);
drop policy if exists "cosmeticos_catalogo_write_todos" on cosmeticos_catalogo;
create policy "cosmeticos_catalogo_write_todos" on cosmeticos_catalogo for all using (true) with check (true);

create table if not exists estudiante_cosmeticos (
  id bigint generated by default as identity primary key,
  estudiante_id bigint references estudiantes(id) on delete cascade,
  cosmetico_id bigint references cosmeticos_catalogo(id) on delete cascade,
  comprado_en timestamptz default now(),
  unique (estudiante_id, cosmetico_id)
);
alter table estudiante_cosmeticos enable row level security;
drop policy if exists "estudiante_cosmeticos_select_todos" on estudiante_cosmeticos;
create policy "estudiante_cosmeticos_select_todos" on estudiante_cosmeticos for select using (true);
drop policy if exists "estudiante_cosmeticos_write_todos" on estudiante_cosmeticos;
create policy "estudiante_cosmeticos_write_todos" on estudiante_cosmeticos for all using (true) with check (true);

alter table progreso add column if not exists marco_equipado_id bigint references cosmeticos_catalogo(id);
alter table progreso add column if not exists titulo_equipado_id bigint references cosmeticos_catalogo(id);

-- Catálogo de ejemplo (editable después)
insert into cosmeticos_catalogo (nombre, tipo, valor, costo_monedas) values
  ('Marco Violeta', 'marco', '#8B5CF6', 20),
  ('Marco Dorado', 'marco', '#F59E0B', 40),
  ('Marco Esmeralda', 'marco', '#22C55E', 30),
  ('Título: Explorador', 'titulo', 'Explorador', 15),
  ('Título: Sabio', 'titulo', 'Sabio del Códice', 35),
  ('Título: Leyenda', 'titulo', 'Leyenda Viviente', 60)
on conflict do nothing;

-- ============================================================
-- Catálogo editable de acciones de gamificación (académico/convivencial/
-- rápido/pilares) — antes estaba fijo en el código, ahora se puede
-- agregar, editar y borrar desde la app.
-- ============================================================
create table if not exists acciones_gamificacion (
  id bigint generated by default as identity primary key,
  docente_id uuid references auth.users(id) on delete set null,
  tab text not null check (tab in ('rapido','academico_pos','academico_neg','pilares','conviv_pos','conviv_neg')),
  label text not null,
  xp integer not null default 0,
  vida integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz default now(),
  unique (tab, label)
);

alter table acciones_gamificacion enable row level security;
drop policy if exists "acciones_gamificacion_select_todos" on acciones_gamificacion;
create policy "acciones_gamificacion_select_todos" on acciones_gamificacion for select using (true);
drop policy if exists "acciones_gamificacion_write_todos" on acciones_gamificacion;
create policy "acciones_gamificacion_write_todos" on acciones_gamificacion for all using (true) with check (true);

-- Migra el catálogo que ya tenías fijo en el código, para no perder nada
insert into acciones_gamificacion (tab, label, xp, vida) values
  ('rapido', 'Participación', 10, 2),
  ('rapido', 'Ayuda a un compañero', 15, 3),
  ('rapido', 'Buena actitud', 10, 3),
  ('rapido', 'Trabajo en equipo', 20, 4),
  ('rapido', 'Uso del celular', -10, -3),
  ('rapido', 'Tarea no entregada', -10, -5),
  ('rapido', 'Actitud negativa', -10, -5),
  ('rapido', 'Llamado de atención', -10, -8),
  ('academico_pos', 'Participación en clase', 10, 2),
  ('academico_pos', 'Tarea entregada a tiempo', 15, 3),
  ('academico_pos', 'Trabajo en equipo destacado', 20, 4),
  ('academico_pos', 'Evaluación sobresaliente', 25, 5),
  ('academico_pos', 'Ayuda a un compañero', 15, 3),
  ('academico_pos', 'Proyecto sobresaliente', 30, 5),
  ('academico_pos', 'Liderazgo en el trabajo de equipo', 20, 4),
  ('academico_pos', 'Creatividad al resolver un problema', 20, 4),
  ('academico_pos', 'Puntualidad constante', 10, 2),
  ('academico_pos', 'Excelente argumentación o redacción', 15, 3),
  ('academico_neg', 'Tarea no entregada', -10, -5),
  ('academico_neg', 'Evaluación insuficiente', -15, -5),
  ('academico_neg', 'Impuntualidad', -5, -2),
  ('academico_neg', 'Copia o fraude académico', -25, -10),
  ('pilares', 'Respeto', 10, 3),
  ('pilares', 'Responsabilidad', 10, 3),
  ('pilares', 'Confiabilidad', 10, 3),
  ('pilares', 'Justicia', 10, 3),
  ('pilares', 'Solidaridad', 10, 3),
  ('pilares', 'Ciudadanía', 10, 3),
  ('conviv_pos', 'Compromiso cumplido', 10, 8),
  ('conviv_pos', 'Mediación pacífica de un conflicto', 15, 6),
  ('conviv_pos', 'Actitud propositiva', 10, 3),
  ('conviv_pos', 'Reconocimiento especial', 20, 5),
  ('conviv_neg', 'Llamado de atención', -10, -8),
  ('conviv_neg', 'Uso del celular sin autorización', -10, -3),
  ('conviv_neg', 'Conflicto con compañeros', -15, -10),
  ('conviv_neg', 'Inasistencia sin excusa', -10, -5),
  ('conviv_neg', 'Consumir alimentos en clase sin permiso', -5, -2),
  ('conviv_neg', 'Incumplimiento del manual de convivencia', -15, -10),
  ('conviv_neg', 'Falta grave / compromiso incumplido', -20, -15)
on conflict do nothing;

-- ============================================================
-- Vincula la Asistencia con la gamificación: al marcar un estado
-- (Presente/Retardo/Falta injustificada/Falta justificada), se
-- aplica el XP/vida configurado para ese código.
-- ============================================================
alter table acciones_gamificacion drop constraint if exists acciones_gamificacion_tab_check;
alter table acciones_gamificacion add constraint acciones_gamificacion_tab_check
  check (tab in ('rapido','academico_pos','academico_neg','pilares','conviv_pos','conviv_neg','asistencia'));
alter table acciones_gamificacion add column if not exists codigo_asistencia text;

-- Guarda qué efecto se aplicó por cada registro de asistencia, para poder
-- revertirlo si se corrige (evita que se acumule sin querer).
alter table asistencia add column if not exists xp_aplicado integer not null default 0;
alter table asistencia add column if not exists vida_aplicada integer not null default 0;

-- Catálogo inicial por código de asistencia (editable después desde la app)
insert into acciones_gamificacion (tab, label, xp, vida, codigo_asistencia) values
  ('asistencia', 'Presente', 0, 0, 'P'),
  ('asistencia', 'Retardo', -5, -5, 'R'),
  ('asistencia', 'Falta injustificada', -10, -15, 'FI'),
  ('asistencia', 'Falta justificada', 0, 0, 'FJ')
on conflict (tab, label) do nothing;
